language: go
sudo: true
git:
  depth: 3
env:
  - DUMP=true # gommon/util/testutil.Dump

go:
  - "1.10"
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep version
  - make dep-install

script:
  - make install
  - make test